create table if not exists public.notification_settings (
  id bigint generated by default as identity primary key,
  channel text not null check (channel in ('whatsapp','email','telegram')),
  enabled boolean not null default false,
  recipient text,
  event_types text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(channel)
);

create table if not exists public.notification_events (
  id uuid primary key default gen_random_uuid(),
  event_key text not null unique,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.notification_deliveries (
  id uuid primary key default gen_random_uuid(),
  event_id uuid references public.notification_events(id) on delete set null,
  channel text not null check (channel in ('whatsapp','email','telegram')),
  recipient text,
  status text not null default 'pending' check (status in ('pending','sent','failed','skipped')),
  provider_message_id text,
  error_message text,
  attempts integer not null default 0,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique(event_id, channel, recipient)
);

create index if not exists idx_notification_deliveries_event on public.notification_deliveries(event_id);
create index if not exists idx_notification_deliveries_status on public.notification_deliveries(status);
create index if not exists idx_notification_events_type on public.notification_events(event_type);

alter table public.notification_settings enable row level security;
alter table public.notification_events enable row level security;
alter table public.notification_deliveries enable row level security;

insert into public.notification_settings (channel, enabled, recipient, event_types)
values
  ('whatsapp', true, '+2349135424851', '{}'),
  ('email', false, 'trademonarchofficial@gmail.com', '{}'),
  ('telegram', false, null, '{}')
on conflict (channel) do update
set recipient = excluded.recipient,
    updated_at = now();
