import express from "express";import cors from "cors";import dotenv from "dotenv";import rateLimit from "express-rate-limit";import crypto from "crypto";import {pool} from "./db.js";import multer from "multer";import fs from "fs";import path from "path";import {auth,passwordHash,passwordCheck,issue} from "./auth.js";import {runQuery} from "./query.js";dotenv.config();
const app=express();app.set("trust proxy",1);app.use(cors({origin:true,credentials:true}));app.use(express.json({limit:"5mb"}));app.use("/api/",rateLimit({windowMs:60000,max:240}));
const out=(res,s,b)=>res.status(s).json(b);
app.get("/api/health",async(_q,res)=>{try{await pool.query("SELECT 1");out(res,200,{ok:true,service:"monarch-codex-hostinger-api",database:"ok"})}catch(e){out(res,503,{ok:false,database:"unavailable"})}});
app.post("/api/auth/signup",async(req,res)=>{try{const {email,password,full_name,phone,referral_code}=req.body||{};if(!email||!password||!full_name||!phone)throw Error("Full name, phone, email and password are required.");const [ex]=await pool.query("SELECT id FROM users WHERE email=? LIMIT 1",[String(email).toLowerCase()]);if(ex.length)return out(res,409,{ok:false,error:"This email is already registered. Please log in instead."});const id=crypto.randomUUID(),hash=await passwordHash(password),uid="MC"+Date.now().toString(36).toUpperCase();await pool.query("INSERT INTO users(id,email,password_hash,full_name,role,active,created_at) VALUES(?,?,?,?,?,1,CURRENT_TIMESTAMP)",[id,String(email).toLowerCase(),hash,full_name,"member"]);await pool.query("INSERT INTO profiles(id,full_name,phone,uid,email,role,status,kyc_status,balance,total_invested,total_earnings,referral_code,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,0,0,0,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",[id,full_name,phone,uid,String(email).toLowerCase(),"member","pending_kyc","pending",referral_code?.trim().toUpperCase()||null]);out(res,200,{ok:true,user:{id,email:String(email).toLowerCase()},session:{access_token:await issue({id,email})}})}catch(e){out(res,400,{ok:false,error:e.message||"Registration failed."})}});
app.post("/api/auth/signin",async(req,res)=>{try{const email=String(req.body?.email||"").toLowerCase(),password=String(req.body?.password||"");const [r]=await pool.query("SELECT id,email,password_hash,active FROM users WHERE email=? LIMIT 1",[email]);if(!r[0]||!r[0].active||!(await passwordCheck(password,r[0].password_hash)))return out(res,401,{ok:false,error:"Invalid login credentials."});out(res,200,{ok:true,user:{id:r[0].id,email:r[0].email},session:{access_token:await issue(r[0])}})}catch(e){out(res,400,{ok:false,error:e.message||"Login failed."})}});
app.post("/api/auth/session",auth,(req,res)=>out(res,200,{ok:true,user:{id:req.user.id,email:req.user.email},session:{access_token:req.headers.authorization.slice(7)}}));
app.post("/api/auth/signout",(_q,res)=>out(res,200,{ok:true}));
app.post("/api/auth/update-password",auth,async(req,res)=>{await pool.query("UPDATE users SET password_hash=? WHERE id=?",[await passwordHash(String(req.body?.password||"")),req.user.id]);out(res,200,{ok:true})});
app.post("/api/query",auth,runQuery);
app.get("/api/public/site-content",async(_req,res)=>{const [r]=await pool.query("SELECT * FROM site_content WHERE id=1 LIMIT 1");out(res,200,{data:r[0]||null,error:null})});
app.post("/api/functions/admin-delete-user",auth,async(req,res)=>{if(!adminRoles.has(String(req.user.role||"").toLowerCase()))return out(res,403,{ok:false,error:"Admin access required."});const uid=String(req.body?.user_id||"");if(!uid||uid===req.user.id)return out(res,403,{ok:false,error:"Invalid target account."});const [target]=await pool.query("SELECT id,role FROM profiles WHERE id=? LIMIT 1",[uid]);if(!target[0])return out(res,404,{ok:false,error:"User not found."});if(adminRoles.has(String(target[0].role||"").toLowerCase()))return out(res,403,{ok:false,error:"Administrator accounts cannot be deleted from member management."});const tables=["referral_bonus_ledger","referrals","earnings","online_cooperative_allocations","payment_receipts","withdrawals","wallet_transactions","wallet_funding_requests","transactions","capital_adjustments","investments","kyc_verifications","notifications","academy_progress","academy_subscriptions","online_cooperative_accounts","sovereign_desk_permissions","telegram_operator_limits","profiles","users"];await pool.query("START TRANSACTION");try{for(const t of tables){const col=t==="users"||t==="profiles"?"id":"user_id";if(t==="referral_bonus_ledger")await pool.query("DELETE FROM "+t+" WHERE referrer_id=? OR referred_user_id=?",[uid,uid]);else if(t==="referrals")await pool.query("DELETE FROM "+t+" WHERE referrer_id=? OR referred_user_id=?",[uid,uid]);else if(t==="sovereign_desk_permissions")await pool.query("DELETE FROM "+t+" WHERE user_id=?",[uid]);else if(t==="telegram_operator_limits")await pool.query("DELETE FROM "+t+" WHERE user_id=?",[uid]);else await pool.query("DELETE FROM "+t+" WHERE "+col+"=?",[uid])}await pool.query("DELETE FROM users WHERE id=?",[uid]);await pool.query("COMMIT");
try{const candidates=[path.join(uploadRoot,uid),path.join(uploadRoot,"wallet",uid)];for(const p of candidates){if(fs.existsSync(p))await fs.promises.rm(p,{recursive:true,force:true})}}catch(storageError){console.error("Hostinger storage cleanup warning:",storageError)}
return out(res,200,{ok:true,mode:"fully-deleted",message:"The user account and associated application data were permanently deleted."})}catch(e){await pool.query("ROLLBACK");return out(res,500,{ok:false,error:"Account deletion failed: "+e.message})}});

const adminRoles=new Set(["admin","super_admin","sovereign_desk","sovereign-desk","kyc_admin","payment_admin","support_admin"]);
app.post("/api/rpc",auth,async(req,res)=>{const {name,args={}}=req.body||{};try{
if(name==="update_my_profile"){const d={display_username:args.p_display_username??null,phone:args.p_phone,avatar_url:args.p_avatar_url??null,withdrawal_account_name:args.p_withdrawal_account_name??null,withdrawal_account_number:args.p_withdrawal_account_number??null,withdrawal_bank:args.p_withdrawal_bank??null};if(args.p_full_name!==undefined)d.full_name=args.p_full_name;const keys=Object.keys(d);await pool.query("UPDATE profiles SET "+keys.map(k=>k+"=?").join(",")+",updated_at=CURRENT_TIMESTAMP WHERE id=?",keys.map(k=>d[k]).concat(req.user.id));const [r]=await pool.query("SELECT * FROM profiles WHERE id=?",[req.user.id]);return out(res,200,{data:r[0]||null})}
if(name==="start_academy_course"||name==="complete_academy_course"){const course=args.p_course_id;const status=name==="complete_academy_course"?"completed":"in_progress";const [ex]=await pool.query("SELECT id FROM academy_progress WHERE user_id=? AND course_id=? LIMIT 1",[req.user.id,course]);if(ex[0])await pool.query("UPDATE academy_progress SET status=?,completed_at="+(status==="completed"?"CURRENT_TIMESTAMP":"NULL")+",updated_at=CURRENT_TIMESTAMP WHERE id=?",[status,ex[0].id]);else await pool.query("INSERT INTO academy_progress(id,user_id,course_id,status,started_at,updated_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",[crypto.randomUUID(),req.user.id,course,status]);return out(res,200,{data:{ok:true,status}})}
if(name==="request_academy_subscription"){const [s]=await pool.query("SELECT academy_price,currency,active FROM academy_settings WHERE id=1 LIMIT 1");const [p]=await pool.query("SELECT balance FROM profiles WHERE id=?",[req.user.id]);const amount=Number(s[0]?.academy_price||0),fee=Math.round(amount*.02*100)/100;if(!s[0]?.active)return out(res,400,{ok:false,error:"Academy access is currently unavailable."});if(Number(p[0]?.balance||0)<amount+fee)return out(res,400,{ok:false,error:"Insufficient wallet balance."});await pool.query("START TRANSACTION");try{await pool.query("UPDATE profiles SET balance=balance-? WHERE id=? AND balance>=?",[amount+fee,req.user.id,amount+fee]);await pool.query("INSERT INTO academy_subscriptions(id,user_id,amount,fee,status,created_at,updated_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",[crypto.randomUUID(),req.user.id,amount,fee,"pending"]);await pool.query("COMMIT")}catch(e){await pool.query("ROLLBACK");throw e}return out(res,200,{data:{ok:true,status:"pending"}})}
if(name==="approve_academy_subscription"||name==="reject_academy_subscription"){if(!adminRoles.has(String(req.user.role||"").toLowerCase()))return out(res,403,{ok:false,error:"Admin access required."});const id=args.p_subscription_id;const [r]=await pool.query("SELECT * FROM academy_subscriptions WHERE id=? LIMIT 1",[id]);if(!r[0])return out(res,404,{ok:false,error:"Subscription not found."});const approved=name.startsWith("approve");await pool.query("UPDATE academy_subscriptions SET status=?,admin_reason=?,reviewed_by=?,approved_at="+(approved?"CURRENT_TIMESTAMP":"NULL")+",rejected_at="+(approved?"NULL":"CURRENT_TIMESTAMP")+",updated_at=CURRENT_TIMESTAMP WHERE id=?", [approved?"approved":"rejected",args.p_admin_reason||null,req.user.id,id]);if(!approved)await pool.query("UPDATE profiles SET balance=balance+? WHERE id=?",[Number(r[0].amount)+Number(r[0].fee||0),r[0].user_id]);return out(res,200,{data:{ok:true,status:approved?"approved":"rejected"}})}
if(name==="purchase_investment_from_wallet"){const [p]=await pool.query("SELECT id,name,amount,active FROM packages WHERE id=? LIMIT 1",[args.p_package_id]);const [u]=await pool.query("SELECT balance FROM profiles WHERE id=?",[req.user.id]);if(!p[0]||!p[0].active)return out(res,400,{ok:false,error:"Investment package is unavailable."});const amount=Number(p[0].amount),fee=1;if(Number(u[0]?.balance||0)<amount+fee)return out(res,400,{ok:false,error:"Insufficient wallet balance."});const id=crypto.randomUUID();await pool.query("START TRANSACTION");try{await pool.query("UPDATE profiles SET balance=balance-?,total_invested=total_invested+? WHERE id=? AND balance>=?",[amount+fee,amount,req.user.id,amount+fee]);await pool.query("INSERT INTO investments(id,user_id,package_name,amount,payment_method,status,created_at,method,fee) VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP,?,?)",[id,req.user.id,p[0].name,amount,"wallet","pending","wallet",fee]);await pool.query("COMMIT")}catch(e){await pool.query("ROLLBACK");throw e}const [b]=await pool.query("SELECT balance FROM profiles WHERE id=?",[req.user.id]);return out(res,200,{data:{ok:true,balance:Number(b[0]?.balance||0),investment_id:id}})}
if(name==="approve_investment_request"||name==="reject_investment_request"){if(!adminRoles.has(String(req.user.role||"").toLowerCase()))return out(res,403,{ok:false,error:"Admin access required."});const id=args.p_investment_id;const [r]=await pool.query("SELECT * FROM investments WHERE id=? LIMIT 1",[id]);if(!r[0])return out(res,404,{ok:false,error:"Investment not found."});const approved=name.startsWith("approve");await pool.query("UPDATE investments SET status=?,approved_at="+(approved?"CURRENT_TIMESTAMP":"NULL"),note=? WHERE id=?",[approved?"approved":"rejected",args.p_admin_reason||null,id]);if(!approved)await pool.query("UPDATE profiles SET balance=balance+? WHERE id=?",[Number(r[0].amount)+Number(r[0].fee||0),r[0].user_id]);return out(res,200,{data:{ok:true,status:approved?"approved":"rejected"}})}
if(name==="approve_wallet_funding"||name==="reject_wallet_funding"){if(!adminRoles.has(String(req.user.role||"").toLowerCase()))return out(res,403,{ok:false,error:"Admin access required."});const id=args.p_request_id;const [r]=await pool.query("SELECT * FROM wallet_funding_requests WHERE id=? LIMIT 1",[id]);if(!r[0])return out(res,404,{ok:false,error:"Funding request not found."});const approved=name.startsWith("approve");await pool.query("UPDATE wallet_funding_requests SET status=?,admin_note=?,reviewed_by=?,reviewed_at=CURRENT_TIMESTAMP WHERE id=?",[approved?"approved":"rejected",args.p_admin_note||null,req.user.id,id]);if(approved){const [u]=await pool.query("SELECT balance FROM profiles WHERE id=?",[r[0].user_id]);const before=Number(u[0]?.balance||0),amount=Number(r[0].amount);await pool.query("UPDATE profiles SET balance=balance+? WHERE id=?",[amount,r[0].user_id]);await pool.query("INSERT INTO wallet_transactions(id,user_id,direction,amount,fee,balance_before,balance_after,source_type,reference_id,description,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)",[crypto.randomUUID(),r[0].user_id,"credit",amount,Number(r[0].fee||0),before,before+amount,"wallet_funding",id,"Wallet funding approved",req.user.id])}return out(res,200,{data:{ok:true,status:approved?"approved":"rejected"}})}
if(name==="sovereign_add_profit"){if(!adminRoles.has(String(req.user.role||"").toLowerCase()))return out(res,403,{ok:false,error:"Admin access required."});const uid=args.p_user_id,amount=Number(args.p_amount||0);if(amount<=0)return out(res,400,{ok:false,error:"Profit amount must be greater than zero."});const [u]=await pool.query("SELECT balance,total_earnings FROM profiles WHERE id=?",[uid]);if(!u[0])return out(res,404,{ok:false,error:"Member not found."});const eid=crypto.randomUUID();await pool.query("INSERT INTO earnings(id,user_id,amount,description,status,created_at,updated_at,type,source_investment_id,profit_month) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,?,?,?)",[eid,uid,amount,args.p_description||"Sovereign Desk profit","approved","profit",args.p_source_investment_id||null,args.p_profit_month||new Date().toISOString().slice(0,10)]);await pool.query("UPDATE profiles SET balance=balance+?,total_earnings=total_earnings+? WHERE id=?",[amount,amount,uid]);const [e]=await pool.query("SELECT * FROM earnings WHERE id=?",[eid]);return out(res,200,{data:e[0]})}
return out(res,400,{ok:false,error:"Hostinger RPC handler not implemented: "+name})}catch(e){console.error(e);return out(res,400,{ok:false,error:e.message||"Business operation failed."})}});

const uploadRoot=process.env.UPLOAD_ROOT||path.resolve(process.cwd(),"private-uploads");fs.mkdirSync(uploadRoot,{recursive:true});const upload=multer({storage:multer.diskStorage({destination:(req,file,cb)=>cb(null,uploadRoot),filename:(req,file,cb)=>{const safe=String(req.body.path||file.originalname).replace(/[^A-Za-z0-9._\\/-]/g,"_").replace(/^\\/+/, "");const full=path.join(uploadRoot,safe);fs.mkdirSync(path.dirname(full),{recursive:true});cb(null,safe)}})});
const sign=(bucket,p,exp)=>crypto.createHmac("sha256",process.env.JWT_SECRET).update(bucket+"|"+p+"|"+exp).digest("hex");
app.post("/api/storage/upload",auth,upload.single("file"),(req,res)=>{if(!req.file)return out(res,400,{ok:false,error:"File is required."});const bucket=String(req.body.bucket||"files"),p=String(req.file.filename);out(res,200,{ok:true,path:p,bucket})});
app.get("/api/storage/public",async(req,res)=>{const p=String(req.query.path||"");const file=path.resolve(uploadRoot,p);if(!file.startsWith(path.resolve(uploadRoot)))return res.status(400).end();if(!fs.existsSync(file))return res.status(404).end();res.sendFile(file)});
app.post("/api/storage/signed-create",auth,async(req,res)=>{const bucket=String(req.body?.bucket||""),p=String(req.body?.path||""),seconds=Math.min(Number(req.body?.seconds||300),900);if(!bucket||!p)return out(res,400,{ok:false,error:"Bucket and path are required."});const exp=Math.floor(Date.now()/1000)+seconds;return out(res,200,{ok:true,url:"/api/storage/signed?bucket="+encodeURIComponent(bucket)+"&path="+encodeURIComponent(p)+"&exp="+exp+"&sig="+sign(bucket,p,exp)})});
app.get("/api/storage/signed",async(req,res)=>{const bucket=String(req.query.bucket||""),p=String(req.query.path||""),exp=Number(req.query.exp||0),sig=String(req.query.sig||"");if(!bucket||!p||Date.now()/1000>exp||sig!==sign(bucket,p,exp))return res.status(403).json({ok:false,error:"Invalid or expired file link."});const file=path.resolve(uploadRoot,p);if(!file.startsWith(path.resolve(uploadRoot))||!fs.existsSync(file))return res.status(404).end();res.sendFile(file)});
const port=Number(process.env.PORT||3000);app.listen(port,()=>console.log("MONARCH CODEX API listening on "+port));