const { pool } = require("./db.js");
const ADMIN=new Set(["admin","super_admin","sovereign_desk","sovereign-desk","kyc_admin","payment_admin","support_admin"]);
const TABLES=new Set(["academy_courses","academy_lessons","academy_progress","academy_settings","academy_subscriptions","capital_adjustments","earnings","email_logs","investments","kyc_verifications","notification_deliveries","notification_events","notification_settings","notifications","online_cooperative_accounts","online_cooperative_allocations","online_cooperative_audit_logs","packages","payment_destinations","payment_details","payment_receipts","profiles","referral_bonus_ledger","referrals","site_content","sovereign_desk_audit_logs","sovereign_desk_permissions","telegram_access","telegram_account_links","telegram_chat_assignments","telegram_chats","telegram_join_requests","telegram_logs","telegram_members","telegram_operator_limits","telegram_settings","telegram_signal_events","telegram_signals","testimonies","transaction_fee_settings","transactions","wallet_funding_requests","wallet_transactions","withdrawals"]);
function admin(u){return ADMIN.has(String(u.role||"").toLowerCase())}
function cols(s){if(!s||s==="*")return "*";return String(s).split(",").map(x=>x.trim()).filter(x=>/^[A-Za-z0-9_]+$/.test(x)).join(",")}
function own(t){return ["profiles","academy_progress","academy_subscriptions","investments","earnings","withdrawals","transactions","wallet_funding_requests","wallet_transactions","notifications","kyc_verifications","payment_receipts","online_cooperative_accounts","online_cooperative_allocations"].includes(t)}
async function runQuery(req,res){const x=req.body||{},t=x.table;if(!TABLES.has(t))return res.status(400).json({ok:false,error:"Table unavailable."});const op=x.op||"select",fs=x.filters||[],isAdmin=admin(req.user);
if(op==="select"){let sql="SELECT "+cols(x.select)+" FROM "+t+" WHERE 1=1",args=[];for(const f of fs){if(!/^[A-Za-z0-9_]+$/.test(f.column))continue;if(f.op==="is"){sql+=" AND "+f.column+(f.value===null?" IS NULL":" IS NOT NULL")}else{sql+=" AND "+f.column+" "+(f.op==="neq"?"<>":"=")+" ?";args.push(f.value)}}if(own(t)&&!isAdmin){if(fs.some(f=>f.column==="user_id"&&String(f.value)!==String(req.user.id)))return res.status(403).json({ok:false,error:"Access denied."});if(!fs.some(f=>f.column==="user_id")){sql+=" AND user_id=?";args.push(req.user.id)}}if(x.order&&/^[A-Za-z0-9_]+$/.test(x.order.column))sql+=" ORDER BY "+x.order.column+" "+(x.order.ascending===false?"DESC":"ASC");if(Number(x.limit)>0)sql+=" LIMIT "+Math.min(Number(x.limit),500);const [rows]=await pool.query(sql,args);return res.json({data:rows,error:null})}
if(!isAdmin&&op!=="insert"&&!(t==="profiles"&&fs.some(f=>f.column==="id"&&String(f.value)===String(req.user.id))))return res.status(403).json({ok:false,error:"Admin access required."});
if(op==="insert"){const d={...(x.data||{})};if(own(t)&&!isAdmin)d.user_id=req.user.id;const keys=Object.keys(d).filter(k=>/^[A-Za-z0-9_]+$/.test(k));if(!keys.length)return res.status(400).json({ok:false,error:"No data."});const [r]=await pool.query("INSERT INTO "+t+" ("+keys.join(",")+") VALUES ("+keys.map(()=>"?").join(",")+")",keys.map(k=>d[k]));return res.json({data:{...d,id:r.insertId},error:null})}
if(op==="update"||op==="delete"){let sql=(op==="delete"?"DELETE FROM ":"UPDATE ")+t,args=[];if(op==="update"){const keys=Object.keys(x.data||{}).filter(k=>/^[A-Za-z0-9_]+$/.test(k));sql+=" SET "+keys.map(k=>k+"=?").join(",");args=keys.map(k=>x.data[k])}sql+=" WHERE 1=1";for(const f of fs){if(/^[A-Za-z0-9_]+$/.test(f.column)){sql+=" AND "+f.column+"=?";args.push(f.value)}}if(own(t)&&!isAdmin&&!fs.some(f=>f.column==="user_id")){sql+=" AND user_id=?";args.push(req.user.id)}await pool.query(sql,args);return res.json({data:null,error:null})}
return res.status(400).json({ok:false,error:"Unsupported operation."})}
module.exports = { runQuery };
